### ISSUE TITLE
No WIFI symbol on top bar (solved)

### ISSUE THREAD

**Issue by Houdoe** [ManuelMcLure/OctoPrint-WiFiStatus#3] opened 2020-10-12 14:02 UTC
I cannot find a WIFI symbol on the status bar. Does your plugin work on a raspberry?

**Comment by ManuelMcLure** [comment] 2020-10-12 15:59
The plugin should work fine on an RPi. Please check `.octoprint/logs/octoprint.log` for any error messages.

The most common cause of the icon not appearing is if OctoPrint is not running under Python 3.7 or higher. It is not sufficient that Python 3.7 be installed on the Pi - OctoPrint needs to be running on 3.7. See https://github.com/cp2004/Octoprint-Upgrade-To-Py3 for a script that will allow you to upgrade your OctoPrint installation to run on Python 3.

**Comment by ManuelMcLure** [comment] 2020-10-14 21:11
If the above comment answered your question, please close the issue.

**Comment by ltmetalman** [comment] 2020-10-16 03:08
This is one of the first plugins I have seen that is a minimum of python 3 or greater. Might want to make that part of the title lol.

**Comment by cereyanli** [comment] 2020-10-16 10:33
I had same problem and with given instructions ( upgrading py3 ) issue has beeen solved

**Comment by ltmetalman** [comment] 2020-10-16 10:37
> I had same problem and with given instructions ( upgrading py3 ) issue has beeen solved

The problem is that this isn't a solved issue, it wasn't an issue to begin with, it's just people that refuse to read, and don't keep up to date with the technology they are using.

**Comment by ManuelMcLure** [comment] 2020-10-16 16:40
This plugin is not and will never be Python 2 compatible. The new issue template now explains that in detail.

**Closed as completed by ManuelMcLure** 2020-10-16 16:40 UTC
Labels: wontfix
